# Generated by Django 5.2 on 2025-04-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_variation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
